// LOGIN
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REMOVE_LOGIN_ERROR = 'REMOVE_LOGIN_ERROR';
// export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

// LOGOUT
export const LOGOUT_USER = 'LOGOUT_USER';

// REGISTER
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REMOVE_REGISTER_ERROR = 'REMOVE_REGISTER_ERROR';
export const REGISTER_USER_RESET = 'REGISTER_USER_RESET';
