import clasnames from "classnames";
import type { Metadata } from "next";

import SessionProvider from "@/context/Session/SessionProvider";
import ReduxProvider from "@/state/ReduxProvider";
import { Inter } from "next/font/google";

import "./App.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mainClasses = clasnames({
    app_main: true,
  });

  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "white" }}>
        <SessionProvider>
          <ReduxProvider>
            <Header />
            <main className={mainClasses}>{children}</main>
            <Footer />
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
