import clasnames from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./App.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mainClasses = clasnames({
    app_main: true,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={mainClasses}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
